CC:=g++

sourcedir:=source
headerdir:=header
objectdir:=object
dependdir:=depend
binarydir:=binary

debugdir:=debug
releasedir:=release
defaultdir:=

sourceextension:=.cc

# -s flag strips symbols
# not doing this allows a 'client' to run a `gdb main` `bt`
#   which could be useful
defaultflags:= -Wall -Wextra -pedantic -std=c++14 -I./$(headerdir)
# -O2 flag might break things..
releaseflags:= $(defaultflags) -s
debugflags:= $(defaultflags) -DDEBUG -ggdb3

name:=main

builds:=default debug release

all:debug release

#TODO:investigate using -fbranch-probabilities
#website appears to be a useful resource:
#  alex.dzyoba.com/linux/profiling-gprof-gcov.html

