#!/bin/bash

OLD=$1
NEW=$2
WD=$(pwd)
DPATH=$WD/$3
BPATH="$WD/bakup"
TFILE="/tmp/out.tmp.$$"

[ ! -d $BPATH ] && mkdir -p $BPATH || :
for f in $DPATH
do
  if [ -f $f -a -r $f ]; then
    /bin/cp -f $f $BPATH
    sed "s/$OLD/$NEW/g" "$f" > $TFILE && mv $TFILE "$f"
  else
    echo "Error: Cannot read $f"
  fi
done

if [ -f $TFILE ]; then
  /bin/rm $TFILE
fi

